### ISSUE TITLE
[fdsnws-event] `StationMagnitude[Contribution]` and `Amplitude`

### ISSUE THREAD

**Issue by damb** [SeisComP/main#28]
Hi devs,

apparently SeisComP's `fdsnws-event` implementation does handle neither `StationMagnitude[Contribution]` nor `Amplitude`, at the time being. Are there any plans to implement the *TODO item*?: https://github.com/SeisComP/main/blob/02c193bc4d6157a35e2c892ab1247de83c40bd80/apps/fdsnws/fdsnws/event.py#L528-L529

**Comment by andres-h** [comment]
We are looking into this, but it does not have very high priority atm. At GEOFON we are not exporting StationMagnitude anyway. Amplitude might be useful.

**Comment by damb** [comment]
Thanks.

I just was curious, since [specs for fdsnws-event](https://www.fdsn.org/webservices/fdsnws-event-1.2.pdf) say that the response for `format=xml` is QuakeML v1.2 and AFAIK QuakeML v1.2 does include the entities mentioned. Of course, nothing forces the implementation to return the corresponding data ...

**Comment by andres-h** [comment]
The format is of course QuakeML v1.2 and not v1.0 or v2.0... AFAIK the spec does not say that these elements MUST be present.

I suppose the TODO item was simply forgotten and we did not notice, because our data does not include the above elements anyway. It is planned to implement the item, but probably not today or tomorrow. BTW, our experts have an opinion that supporting StationMagnitude and Amplitude may have negative impact on the performance, so this will in any case be an optional feature.

**Comment by damb** [comment]
> AFAIK the spec does not say that these elements MUST be present.

I agree.

Thanks for the insights, @andres-h.

**Comment by jsaul** [comment]
If the database the fdsnws-event is served from contains the StationMagnitude and Amplitude objects, it is certainly not far-fetched to expect that these objects are also included in the QuakeML generated fdsnws-event or at least _can_ be.

So this is indeed a TODO item although perhaps not with top priority. Note that the inclusion especially of StationMagnitude is likely to be a rather expensive operation. This might a concern in times of high server traffic.

Anyway, code donations would be highly appreciated. ;)

**Comment by gempa-jabe** [comment]
Closed due to inactivity.
